### PR TITLE
Add step-by-step "Getting Started" section to README

### PR DESCRIPTION
**Pull request by ghost**
### Justification:
- **Reasoning for adding default "hosts" file:** Advanced users can always modify/disregard this file, and having it there by default lets you make the steps to get everything up and running shorter.  Asking a user who's never used ansible before to read through the inventory file documentation seems more than necessary when such a simple file is all that's needed to get started.
- **Reasoning for renaming "example.yml" to "browser.yml":** Similar to above, but advanced users can always do their own thing. Calling it "browser.yml" (IMO) makes it more clear that no changes are necessary on the user's part to get things up and running.
### Areas that still need work:
- I'm not 100% sure the "basic prerequisites" section (spice, qemu, python2) is complete. I'll double check this next time I have a clean arch installation to try with.
- I didn't do anything with your /dev/random suggestion here
- Calling ansible-playbook with "python2 $ANSIBLE_DIR/bin/ansible-playbook" is ugly but it's how I've been doing things. Could definitely be improved if you want to change things to do it the right way.
- The extra "reboot" at the end of the installation procedure is a bit weird. I haven't dug in to see why it's necessary, but it is. If you know why and can tweak things to remove it, that'd be nice.

I'll try to add some additional info for how things differ when using Debian as your host distro, but no ETA for that.

Let me know what you think.

### CODE REVIEW

**Comment by ghost** [comment]
Also, you'll want to change the git URI from https://github.com/andy11/alpine-appvm.git back to https://github.com/mutantmonkey/alpine-appvm.git in your branch. 

Not sure if there's a way via Github to do this automatically with some kind of reference to the README's own repo.

**Comment by mutantmonkey** [comment]
Thanks, I'll look over this and merge it soon hopefully. I don't believe there's a way for GitHub to have a self-referential URL in a readme that auto-updates.

**Comment by ghost** [comment]
I pulled your latest changes in and added "sshpass" to the dependency list. I verified this covers everything you  need to get the appvm running on a brand new arch linux install (assumes you follow the steps on the arch wiki).

**Comment by mutantmonkey** [comment]
Awesome, sorry it's taking me so long to get to this. I'll hopefully be able to take a look sometime this week.

**Comment by conorsch** [comment]
@mutantmonkey Why on earth is this not merged? It provides a lot of insight on how the project should be used.

**Pull request merged**
